import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

//providers
import { QueryClientProvider } from '@tanstack/react-query'
import { ProductsQuery } from './data/ProductsQuery'

const montserrat = Montserrat({ subsets: ['latin'], weight: ['300','400', '500', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <QueryClientProvider client={ProductsQuery}>
        {children}
        </QueryClientProvider>
        </body>
    </html>
  )
}
